version: "3"

services:
  database:
    image: mongo
    container_name: mongo-iot
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=iotdb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password      
    volumes:
      - ./config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro      
    networks:
      - network-name

networks:
    network-name:
      name: uniovi
